First commit.

diff --git a/.github/workflows/autopopulation.yml b/.github/workflows/autopopulation.yml
--- a/.github/workflows/autopopulation.yml
+++ b/.github/workflows/autopopulation.yml
@@ -4,10 +4,10 @@ on:
   pull_request:
     types: [closed]
     branches:
-      - main
+      - duplicate
   push:
     branches:
-      - main
+      - duplicate
 
 jobs:
   sync-instances:
@@ -28,14 +28,10 @@ jobs:
       - name: Process and Sync Changes in instance Files
         id: process_sync_instances
         run: |
-          set -x
-          # Fetch the base branch for comparison
-          GITHUB_BASE_REF="${GITHUB_BASE_REF:-main}"
-          git fetch origin $GITHUB_BASE_REF
-          echo “$GITHUB_BASE_REF”
+          git checkout HEAD
 
           # Compare the changes between the PR branch and the base branch
-          git diff --name-only --diff-filter=AM origin/$GITHUB_BASE_REF...HEAD | grep '\.jsonld$' > changed_files.txt || true
+          git diff --name-only --diff-filter=AM HEAD^ HEAD | grep '\.jsonld$' > changed_files.txt || true
           
           cat changed_files.txt
           declare -A seen_files
@@ -44,7 +40,7 @@ jobs:
           # Check if there are any changed .jsonld files
           if [ -s changed_files.txt ]; then
             while IFS= read -r file; do
-              FILE_MODULE=$(echo "$file" | cut -d'/' -f3-4)
+              FILE_MODULE=$(dirname "$file" | cut -d'/' -f3-)
               FILE_NAME=$(basename "$file")
               MODULE_NAME="$FILE_MODULE/$FILE_NAME"
               
@@ -59,13 +55,13 @@ jobs:
             done < changed_files.txt
           fi
           
-          # TODO add when files will be updated
-          # wget https://raw.githubusercontent.com/openMetadataInitiative/openMINDS/refs/heads/main/vocab/types.json -P .github/templates/
-          # wget https://raw.githubusercontent.com/openMetadataInitiative/openMINDS/refs/heads/main/vocab/properties.json -P .github/templates/
-          
           if [ ${#modified_jsons[@]} -gt 0 ]; then
             MAIN_FOLDER="instances"
-
+            
+            # Add template files
+            wget https://raw.githubusercontent.com/openMetadataInitiative/openMINDS/refs/heads/main/vocab/types.json -P .github/templates/
+            wget https://raw.githubusercontent.com/openMetadataInitiative/openMINDS/refs/heads/main/vocab/properties.json -P .github/templates/
+            
             for FILE in "${!modified_jsons[@]}"; do
               FILE_VERSION="${modified_jsons[$FILE]}"
               FILE_NAME=$(basename "$FILE")
@@ -82,8 +78,9 @@ jobs:
               done
             done
             
-            # rm .github/templates/types.json
-            # rm .github/templates/properties.json
+            # Cleanup of template files
+            rm .github/templates/types.json
+            rm .github/templates/properties.json
             
             # Commit changes if any instance files were modified
             # git config --global user.name "openMINDS pipeline"
@@ -97,7 +94,11 @@ jobs:
             git config --global user.email "gazzotti.raphael@gmail.com"
             git add $MAIN_FOLDER/**/*.jsonld
             git commit -m "Population of properties from modified instance files"
-            git push origin HEAD:duplicated
+            
+            # Fetch latest changes from remote and rebase before pushing
+            git fetch origin duplicate
+            git rebase origin/duplicate
+            git push origin HEAD:duplicate
           else
             echo "No JSON-LD files modified."
           fi
